### PR TITLE
Fix the performance issue via initializing RowEncoder only once

### LINKED ISSUE #35: StateStoreReaderRDD very slow reading the state
A state of roughly 300000 records whose schema is similar to (sorry, can't give full details)
```scala
case class State(
  s1: String,
  s2: String,
  s3: String,
  b1: Boolean,
  i1: Int,
  l1: Long,
  ss1: Set[String],
  si1: Set[Long],
  t1: Timestamp,
  t2: Timestamp,
  sd1: Set[Date],
)
```
takes 37 minutes to be read on a cluster with 
```
driver: 4 cores @ 24 Gb ram
4 executors: 8 cores @ 16 Gb ram
```
which is way too long. 
My [hacky code](https://github.com/chermenin/spark-states/issues/15#issuecomment-629574930) that I posted in `spark-states` issue takes just a few seconds.

I think the problem is in 
```scala
object StateStoreRelation {
  def unifyStateRowPair(schema: StructType)(pair: (UnsafeRow, UnsafeRow)): Row = {
    val row = new GenericInternalRow(2)
    row.update(0, pair._1)
    row.update(1, pair._2)

    val encoder: ExpressionEncoder[Row] = RowEncoder(schema).resolveAndBind()
    encoder.fromRow(row)
  }
}
```
that you use as:
```scala
  override def buildScan(): RDD[Row] = {
   ...

    val rdd = new StateStoreReaderRDD(session, keySchema, valueSchema,
      resolvedCpLocation, batchId, operatorId, storeName)
    rdd.map(StateStoreRelation.unifyStateRowPair(schema))
  }
```

I think you're creating an `Encoder` for every Row(in the `.map`). I'm testing my assumption and I'll create a PR soon if this is the case. 

Also, in `StateStoreReaderRDD.scala` you do 
```scala
val iter = store.iterator().map(pair => (pair.key, pair.value))
```
So one `.map` here, and one in 
```scala
    rdd.map(StateStoreRelation.unifyStateRowPair(schema))
```
Why not returning an `RDD[Row]` directly from `StateStoreReaderRDD` instead?

### PR DESCRIPTION
**Pull request by redsk**
Fixes #35 .

Also, unrelated, in `StateStoreRelation.scala` you have
```scala

class StateStoreRelation(
    session: SparkSession,
    keySchema: StructType,
    valueSchema: StructType,
    stateCheckpointLocation: String,
    batchId: Int,
    operatorId: Int,
    storeName: String = StateStoreId.DEFAULT_STORE_NAME,
    sourceOptions: Map[String, String]) extends BaseRelation with TableScan with Logging
```

but `sourceOptions` is unused. Should that be fixed?

### CODE REVIEW

**Comment by redsk** [comment]
There are two commits, the first fixes the performance issues. The seconds changes `StateStoreReaderRDD` from `RDD[(UnsafeRow, UnsafeRow)]` to `RDD[Row]` and simplifies the code. 

Answering this:

> > Why not returning an RDD[Row] directly from StateStoreReaderRDD instead?
> 
> I'd like to make `StateStoreReaderRDD` just do read from the state and provide the same, in case the class can be used for multiple purposes. Looks like it's OK to provide `Iterator[UnsafeRowPair]` instead of `Iterator[(UnsafeRow, UnsafeRow)]` for `StateStoreReaderRDD.compute()` to avoid creating tuples.

But this way you map twice instead of once. Maybe we can define something like 
```scala
StateStoreReaderRDD extends RDD[(UnsafeRow, UnsafeRow)]
// and
StateStoreReaderRDDRow extends StateStoreReaderRDD
```
with the latter redefining just one function of `StateStoreReaderRDD` so we get the best of both words

**Comment by HeartSaVioR** [comment]
Changing to `Iterator[UnsafeRowPair]` gets rid of map in RDD side, hence we'll end up mapping only once.

The point is that the schema `(key, value)` is specific to the relation, and it's ideal to avoid propagate the information to the RDD, if we would like to consider reusability. I agree it may not be used in other purpose, but both ways end up with mapping only once (no difference), hence I'd like to keep the possibility.

**Comment by HeartSaVioR** [comment]
But I was away from this project more than a year, so I might be wrong, e.g. it may not be possible to change to `Iterator[UnsafeRowPair]`. If that's the case, I agree your proposal looks better than current.

**Comment by redsk** [comment]
I'm a bit afraid of returning `Iterator[UnsafeRowPair]` because `UnsafeRowPair` is "reusable"; from `org.apache.spark.sql.execution.streaming.state.StateStore.scala`:
```scala
/** Mutable, and reusable class for representing a pair of UnsafeRows. */
class UnsafeRowPair(var key: UnsafeRow = null, var value: UnsafeRow = null) {
  def withRows(key: UnsafeRow, value: UnsafeRow): UnsafeRowPair = {
    this.key = key
    this.value = value
    this
  }
}
```
So we might end up needing to make a copy of it somehow

File: src/main/scala/net/heartsavior/spark/sql/state/StateStoreRelation.scala [hunk 1]
```diff
@@ -41,9 +40,7 @@ class StateStoreRelation(
 
   override def sqlContext: SQLContext = session.sqlContext
 
-  override def schema: StructType = new StructType()
-    .add("key", StructType(keySchema.fields), nullable = false)
-    .add("value", StructType(valueSchema.fields), nullable = false)
+  override def schema: StructType = SchemaUtil.schema(keySchema, valueSchema)
```
Comment (HeartSaVioR) [inline src/main/scala/net/heartsavior/spark/sql/state/StateStoreRelation.scala]: The schema information is specific to here, hence good to leave it here as it is. The method name `schema` is not clear to determine "which" schema it denotes.

**Comment by HeartSaVioR** [comment]
> but sourceOptions is unused. Should that be fixed?

Yes please. It seems to be redundant. Nice finding.

File: src/main/scala/net/heartsavior/spark/sql/state/StateStoreRelation.scala (hunk 1 above)
Comment (redsk) [reply src/main/scala/net/heartsavior/spark/sql/state/StateStoreRelation.scala]: I moved it to `SchemaUtil` because I need it both in `StateStoreRelation` and `StateStoreReaderRDD`. I agree that the name `schema` is not ideal. would `keyValuePairSchema` work better for you?

Comment (HeartSaVioR) [reply src/main/scala/net/heartsavior/spark/sql/state/StateStoreRelation.scala]: Sounds OK to me.

File: src/main/scala/net/heartsavior/spark/sql/state/StateStoreReaderRDD.scala [hunk 2]
```diff
@@ -47,14 +49,14 @@ class StateStoreReaderRDD(
     batchId: Long,
     operatorId: Long,
     storeName: String)
-  extends RDD[(UnsafeRow, UnsafeRow)](session.sparkContext, Nil) {
+  extends RDD[Row](session.sparkContext, Nil) {
```
Comment (HeartSaVioR) [inline src/main/scala/net/heartsavior/spark/sql/state/StateStoreReaderRDD.scala:52]: Let's update the class doc; An RDD that reads (key, value) pair of state and provides rows having columns (key, value).

**Comment by redsk** [comment]
Unrelated, 

```scala
        throw new IllegalStateException(s"Checkpoint location should not be exist. " +
          s"Path: $checkpointPath")
// and
case None => throw new IllegalStateException("offset log for batch should be exist")
```
I think it should be `Checkpoint location should not exist` and `offset log for batch should exist` with no `be`.

**Comment by HeartSaVioR** [comment]
I'd rather handle it as different PR but given it's a small refinement I'm OK to include them in this PR as well.

**Review by HeartSaVioR — APPROVED** [review]
LGTM. I assume you've gone through the manual test to verify the patch.

**Comment by redsk** [comment]
Yes, before the "cosmetic" commits. It's roughly 2000 times faster now.

**Comment by HeartSaVioR** [comment]
Great! Yeah that's inside critical path and I made a mistake on critical path which affects pretty badly. Thanks for fixing the bug!

**Comment by redsk** [comment]
You're more than welcome! Can you please release a new version after merge? That would save me some time.

**Comment by HeartSaVioR** [comment]
Sure! I'll pull the change and release 0.3.1. Keep you posted here.

**Comment by HeartSaVioR** [comment]
@redsk Just pushed "release" for 0.4.0! It may need some time to sync with other maven repositories. Please check it out.

I picked the version 0.4.0 (next minor) as I feel it's a critical bug fix which invalidates needs of previous releases. Thanks again for your contribution!

**Comment by redsk** [comment]
Already available on Maven Central:
- https://repo1.maven.org/maven2/net/heartsavior/spark/spark-state-tools_2.12/0.4.0/

**Comment by redsk** [comment]
I confirm everything is working fine with `0.4.0` with prod loads.
