### PR TITLE
Fix serializable configuration

### LINKED ISSUE #32: java.lang.NullPointerException while accessing Hadoop configuration when reading the state as batch query
Hi @HeartSaVioR ,

I'm trying to read the state using the batch query, as in 

```scala
val operatorId = 0
val batchId = 1 // the version of state for the output of batch is batchId + 1

// Here we assume 'spark' as SparkSession
val stateReadDf = spark.read
  .format("state")
  .schema(stateSchema)
  .option(StateStoreDataSourceProvider.PARAM_CHECKPOINT_LOCATION,
    new Path(checkpointRoot, "state").getAbsolutePath)
  .option(StateStoreDataSourceProvider.PARAM_VERSION, batchId + 1)
  .option(StateStoreDataSourceProvider.PARAM_OPERATOR_ID, operatorId)
  .load()
```

If run this query on a Driver only in standalone mode (or in the unittests) all works perfectly. However, if I use a real cluster with executors, I get a NullPointerException:
```
java.lang.NullPointerException
  org.apache.spark.sql.execution.streaming.CheckpointFileManager$.create(CheckpointFileManager.scala:178)
  org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.fm$lzycompute(HDFSBackedStateStoreProvider.scala:265)
  org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$fm(HDFSBackedStateStoreProvider.scala:265)
  org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.init(HDFSBackedStateStoreProvider.scala:224)
  org.apache.spark.sql.execution.streaming.state.StateStoreProvider$.createAndInit(StateStore.scala:230)
  org.apache.spark.sql.execution.streaming.state.StateStore$.$anonfun$get$1(StateStore.scala:366)
  scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
  org.apache.spark.sql.execution.streaming.state.StateStore$.get(StateStore.scala:365)
  net.heartsavior.spark.sql.state.StateStoreReaderRDD.compute(StateStoreReaderRDD.scala:67)
  org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
  org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
  org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
...
```

When checking Spark code at `CheckpointFileManager.scala:178` I see:
```scala
val fileManagerClass = hadoopConf.get(
      SQLConf.STREAMING_CHECKPOINT_FILE_MANAGER_CLASS.parent.key)
```

I've also tried with `chermenin/spark-states` (which is actually what I tried first) and it also failed with a similar exception in 

```
java.lang.NullPointerException
	at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateStoreProvider.init(RocksDbStateStoreProvider.scala:359)
	at org.apache.spark.sql.execution.streaming.state.StateStoreProvider$.createAndInit(StateStore.scala:230)
	at org.apache.spark.sql.execution.streaming.state.StateStore$.$anonfun$get$1(StateStore.scala:366)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at org.apache.spark.sql.execution.streaming.state.StateStore$.get(StateStore.scala:365)
	at net.heartsavior.spark.sql.state.StateStoreReaderRDD.compute(StateStoreReaderRDD.scala:67)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	...
```

`RocksDbStateStoreProvider.scala:359` also reads the Hadoop Conf:
```scala
this.tempDir = getTempDir(getTempPrefix(hadoopConf.get("spark.app.name")), "")
```

So I think the problem could be in `StateStoreReaderRDD.scala`:
```scala
  // A Hadoop Configuration can be about 10 KB, which is pretty big, so broadcast it
  private val hadoopConfBroadcast = session.sparkContext.broadcast(
    new SerializableConfiguration(session.sessionState.newHadoopConf()))

  override def compute(split: Partition, context: TaskContext): Iterator[(UnsafeRow, UnsafeRow)] = {
    split match {
      case p: StateStorePartition =>
        val stateStoreId = StateStoreId(stateCheckpointRootLocation, operatorId,
          p.partition, storeName)
        val stateStoreProviderId = StateStoreProviderId(stateStoreId, p.queryId)

        val store = StateStore.get(stateStoreProviderId, keySchema, valueSchema,
          indexOrdinal = None, version = batchId, storeConf = storeConf,
          hadoopConf = hadoopConfBroadcast.value.value)

        val iter = store.iterator().map(pair => (pair.key, pair.value))

        // close state store provider after using
        StateStore.unload(stateStoreProviderId)

        iter

      case e => throw new IllegalStateException("Expected StateStorePartition but other type of " +
        s"partition passed - $e")
    }
  }
```

I think that for some reason `hadoopConfBroadcast` contains a null value.
It's a bit hard to debug as the problem does no occur if the code is executed locally in debug mode (say in Intellij) or even in Spark in driver only mode (in the end, it's the same JVM this way so the conf does not need to be broadcasted for real...)

Any idea?

### PR DESCRIPTION
**Pull request by redsk**
Fixes #32 . I'm not sure why wrapping the `SerializableConfiguration` works, but I remembered that I used the same solution for a similar use case

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Thanks for dealing with the issue quickly. Let's isolate PRs so that we can review individually. The last commit (e5a4f83) doesn't (and shouldn't) depend on the sbt PR.

**Comment by redsk** [comment]
Sorry, my bad, I didn't realise I did that. I'll fix it.

File: src/main/scala/net/heartsavior/spark/sql/state/StateStoreWriter.scala [hunk 1]
```diff
@@ -45,8 +45,7 @@ class StateStoreWriter(
   private val storeConf = new StateStoreConf(session.sessionState.conf)
 
   // A Hadoop Configuration can be about 10 KB, which is pretty big, so broadcast it
-  private val hadoopConfBroadcast = session.sparkContext.broadcast(
-    new SerializableConfiguration(session.sessionState.newHadoopConf()))
+  private val hadoopConfBroadcast = new SerializableConfigurationWrapper(session)
```
Comment (HeartSaVioR) [inline src/main/scala/net/heartsavior/spark/sql/state/StateStoreWriter.scala:48]: Would it work if we don't change the entire code but change `session.sessionState.newHadoopConf()` to `session.sparkContext.hadoopConfiguration`? That might be the point where bug hides.

Comment (redsk) [reply src/main/scala/net/heartsavior/spark/sql/state/StateStoreWriter.scala:48]: I tried that first and it didn't work.

Comment (HeartSaVioR) [reply src/main/scala/net/heartsavior/spark/sql/state/StateStoreWriter.scala:48]: Sigh. Thanks for letting me know. Let's add some comment to the wrapper class to avoid missing the needs for the class.

File: src/main/scala/org/apache/spark/sql/hack/SerializableConfigurationWrapper.scala [hunk 2]
```diff
@@ -18,24 +18,18 @@
...
-import org.apache.hadoop.conf.Configuration
-
-import org.apache.spark.util.Utils
+import org.apache.spark.broadcast.Broadcast
+import org.apache.spark.sql.SparkSession
+import org.apache.spark.util.SerializableConfiguration
 
 /**
- * NOTE: This is just a copy & paste of [[org.apache.spark.util.SerializableConfiguration]].
+ * This class was added because without it a NullPointerException was thrown by
```
Comment (HeartSaVioR) [inline src/main/scala/org/apache/spark/sql/hack/SerializableConfigurationWrapper.scala:26]: I'd rather leave the origin issue number with mentioning the approach we tried from Spark code, but I'll refine the comment afterwards so it doesn't matter.

**Comment by HeartSaVioR** [comment]
Thanks for the quick address. Have you gone through the manual tests? 
(I haven't have time to experiment with real cluster for now. May need couple of days from my side, so I'd like to handle this in faith.)
Even better if you were able to run the manual test with RocksDB state store. Thanks!

**Comment by redsk** [comment]
> Thanks for the quick address. Have you gone through the manual tests?
> (I haven't have time to experiment with real cluster for now. May need couple of days from my side, so I'd like to handle this in faith.)
> Even better if you were able to run the manual test with RocksDB state store. Thanks!

If with manual tests you mean those in the [how-to-use](https://github.com/HeartSaVioR/spark-state-tools#how-to-use) section of the `README.md`, I've gone through half of them. I'll do the rest today as I'm using `spark-state-tools` to build a system for work! I'll keep you updated. And yes, I'm using RocksDB state store.

**Comment by HeartSaVioR** [comment]
Oh OK if you've done with any single batch query for the use case that should be fine for rest of the use cases as well. (Assuming the differences between them should be covered by unit tests.)

Let's merge and publish new version (with cross-compiled artifacts), and you can play with the new version and check whether the new version works perfectly. Thanks again!

**Comment by redsk** [comment]
@HeartSaVioR perfect, thanks a lot for the quick merge and also for publishing the new version. That will certainly make my life easier! Cheers!

**Comment by HeartSaVioR** [comment]
I just released the artifacts under version 0.3.0. It may take up to 48 hours to sync up.

https://search.maven.org/artifact/net.heartsavior.spark/spark-state-tools_2.12
https://search.maven.org/artifact/net.heartsavior.spark/spark-state-tools_2.11

Please check the pages occasionally. Cheers!

**Comment by redsk** [comment]
Oh I see, I was trying to download them but I see they are not available yet on Maven central! I guess I'll have to wait a bit further to get the artifacts from there. 

Thanks a lot!

**Comment by redsk** [comment]
They are actually available now:
https://repo1.maven.org/maven2/net/heartsavior/spark/spark-state-tools_2.12/0.3.0/
https://repo1.maven.org/maven2/net/heartsavior/spark/spark-state-tools_2.11/0.3.0/
and they work! 👍

**Comment by HeartSaVioR** [comment]
Superb, that was so fast. Thanks for sharing the news!

**Comment by HeartSaVioR** [comment]
Just to be sure, it would be really appreciated if you could provide some feedbacks after experimenting. Anything like bugs, ideas, etc. are welcome!

**Comment by redsk** [comment]
> Just to be sure, it would be really appreciated if you could provide some feedbacks after experimenting. Anything like bugs, ideas, etc. are welcome!

Everything is working correctly, I can read and write state. 

1. I started a "batch" query (`Trigger.Once`) from a delta table on hdfs.
2. I started a "batch" query (`Trigger.Once`) from a kafka topics till some specific offsets. 
3. I copied the checkpoint of the kafka query without state to a third location.
4. I read states of 1 and 2, merged them with standard spark operations on dataframes.
5. I wrote the state of the third query as the one calculated in 4.
6. I started a normal streaming kafka query using the checkpoints at 3. and the state at 5. and it's working.

The problem is that the reading performance are really poor. I think `StateStoreReaderRDD` is very slow at reading the state for some reason. I'm investigating it and then I'll open an issue.

**Comment by HeartSaVioR** [comment]
I don't know how the RocksDB state store provider has been implemented, but initial load would have time. There may be other characteristics on specific state store provider or external storage (as I just googled and found the issue reports on iterator performance of RocksDB Java), so it'd be worth trial to do the same with HDFS state store provider.

**Comment by redsk** [comment]
No, see #35 , I've found both the problem and the solution, PR shortly.
